qualitio/payments/urls.py
from django.conf.urls.defaults import patterns, include, url

from .views import paypal_ipn

urlpatterns = patterns('',
    url(r'^paypal_ipn/$', paypal_ipn, name="paypal_ipn")
)

qualitio/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.shortcuts import redirect
from django.contrib import admin
admin.autodiscover()

from qualitio import api
from qualitio.organizations.auth.registration.views import RegisterUser, RegisterUserThanks
from qualitio.organizations import views as organization_views


def admin_redirect(request, *args, **kwargs):
    if request.organization:
        site_host = ".".join(request.get_host().split('.')[1:])
        protocol = 'https' if request.is_secure() else 'http'
        return redirect("%s://%s/admin/" % (protocol,site_host))

    return admin.site.index(request, *args, **kwargs)


urlpatterns = patterns('',
                       (r'', include('social_auth.urls')),
                       (r'', include('qualitio.organizations.urls')),
                       (r'', include('qualitio.payments.urls')),

                       url(r'^register/$', RegisterUser.as_view(), name="registration"),
                       url(r'^register/thanks/$',
                           RegisterUserThanks.as_view(), name="registration_thanks"),
                       url(r'^inactive/',
                           organization_views.UserInactive.as_view(), name="inactive"),
                       url(r'^logout/$', 'django.contrib.auth.views.logout',
                           {'next_page' : '/'}, name="logout"),
                       url(r'^login/$', 'django.contrib.auth.views.login',
                           {'template_name': "registration/login.html"}, name="login"),

                       (r'^permission_required/$', 'qualitio.core.permission_required'),

                       (r'^project/(?P<project>[\w-]+)/require/',
                        include('qualitio.require.urls', app_name="require")),
                       (r'^project/(?P<project>[\w-]+)/execute/',
                        include('qualitio.execute.urls', app_name="execute")),
                       (r'^project/(?P<project>[\w-]+)/store/',
                        include('qualitio.store.urls', app_name="store")),
                       (r'^project/(?P<project>[\w-]+)/report/',
                        include('qualitio.report.urls', app_name="report")),
                       (r'^project/(?P<project>[\w-]+)/actions/',
                        include('qualitio.actions.urls')),
                       (r'^project/(?P<project>[\w-]+)/glossary/',
                        include('qualitio.glossary.urls', app_name="glossary")),
                       (r'^project/(?P<project>[\w-]+)/chart/',
                        include('qualitio.chart.urls', app_name="chart")),
                       (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       (r'^admin/$', admin_redirect),
                       (r'^admin/', include(admin.site.urls)),
                       (r'^project/[\w-]+/', include(api.urls)),
                       )


if settings.DEBUG:
    urlpatterns += patterns('',
                            (r'^static/(?P<path>.*)$', 'django.views.static.serve',
                             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
                            )

qualitio/payments/models.py
from django.db import models
from .paypal import PayPal, PayPalException


class Strategy(models.Model):
    name = models.CharField(max_length=64)
    users = models.IntegerField()
    price = models.FloatField(default=0)

    def endpayment(self):
        pass

    def __unicode__(self):
        return self.name

    @classmethod
    def get_default(cls):
        try:
            return cls.objects.all()[0]
        except IndexError:
            return cls.objects.create(
                name="Free",
                users=5,
                price=0
            )

class Profile(models.Model):
    organization = models.OneToOneField('organizations.Organization',
                                        related_name="payment")
    strategy = models.ForeignKey('Strategy')
    paypal_id = models.CharField(max_length=14, blank=True)

    INACTIVE = 0
    PENDING = 1
    ACTIVE = 2
    CANCELED = 3
    
    choices = (
        (INACTIVE, "Inactive"),
        (PENDING, "Pending"),
        (ACTIVE, "Active"),
        (CANCELED, "Canceled")
    )
    
    status = models.PositiveSmallIntegerField(choices=choices, default=0)
    valid_time = models.DateTimeField()
    created_time = models.DateTimeField()

    def __init__(self, *args, **kwargs): 
        super(Profile, self).__init__(*args, **kwargs) 
        self._status = self.status
        if self.strategy_id:
            self._strategy = self.strategy
        else:
            self._strategy = None
    
    def __unicode__(self):
        return "%s :%s" % (self.organization.name,
                           self.strategy.name)

    def is_running(self):
        return self.status in (self.PENDING, self.ACTIVE)

    def cancel(self, **kwargs):
        if self._status in (Profile.PENDING, Profile.ACTIVE):
            try:
                paypal = PayPal()
                paypal.ManageRecurringPaymentsProfileStatus(
                    PROFILEID=self.paypal_id,
                    ACTION="Cancel")
            except PayPalException as e:
                # thats allright, profile was cancled again
                if e.message['L_ERRORCODE0'] not in ('11556', '11551'): 
                    raise e

            if self._status == Profile.PENDING:
                self.status = Profile.INACTIVE
                self.strategy = Strategy.get_default()
                self.paypal_id = ""

            if self._status == Profile.ACTIVE:
                self.status = Profile.CANCELED

            kwargs['cancel_check'] = False
            self.save(**kwargs)
            
        
    def save(self, **kwargs):
        admin_memeber = kwargs.pop('admin_memeber', None)

        if self._strategy:
            if self._strategy != self.strategy and \
               self._strategy.users > self.strategy.users:
            
                from qualitio.organizations.models import OrganizationMember

                members = OrganizationMember.objects.filter(organization=self.organization)
            
                admins = members.filter(role=OrganizationMember.ADMIN)
                others = members.exclude(role=OrganizationMember.ADMIN)

                others.update(role=OrganizationMember.INACTIVE)
            
                if admin_memeber:
                    admins.exclude(pk=admin_memeber.pk).update(role=OrganizationMember.INACTIVE)
                else:
                    first_admin = admins[:1].values_list("id", flat=True)
                    admins.exclude(pk__in=first_admin).update(
                        role=OrganizationMember.INACTIVE)

        cancel_check = kwargs.pop('cancel_check', True)
        if self.status == self.CANCELED and cancel_check:
            self.cancel()
        else:
            super(Profile, self).save(**kwargs)

qualitio/payments/forms.py
from django import forms

from . import countries

class PaymentForm(forms.Form):
    choices = (
        ("Visa","Visa"),
        ("MasterCard","MasterCard"),
        ("Discover", "Discover"),
        ("Amex", "Amex"),
    )
    plan = forms.CharField(widget=forms.HiddenInput)

    CREDITCARDTYPE = forms.ChoiceField(choices=choices, label="Type", required=True)
    ACCT = forms.DecimalField(label="Number", required=True)
    EXPDATE = forms.CharField(label="Expiration date", required=True)
    CVV2 = forms.CharField(label="CCV", required=True)

    FIRSTNAME = forms.CharField(label="Firstname", required=True)
    LASTNAME = forms.CharField(label="Lastname", required=True)
    STREET = forms.CharField(label="Address", required=True)
    CITY = forms.CharField(label="City", required=True)
    STATE = forms.CharField(label="State/Area/Region", required=True)
    ZIP = forms.CharField(label="Zip", required=True)
    COUNTRYCODE = forms.ChoiceField(choices=countries.COUNTRIES, label="Country", required=True)

qualitio/payments/views.py
from datetime import datetime
from dateutil.relativedelta import relativedelta

from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, RedirectView
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.template.loader import render_to_string

from qualitio.organizations.models import Organization

from .paypal import PayPal, PayPalException
from .models import Strategy, Profile
from .forms import PaymentForm

@csrf_exempt
def paypal_ipn(request, *args, **kwargs):
    if not request.method == "POST":
        raise Http404 

    organization_name, strategy_name = request.POST.get('product_name').split(":")

    profile = Profile.objects.get(organization__name=organization_name)
    
    if request.POST.get('txn_type') == 'recurring_payment' and \
       request.POST.get('payment_status') == u'Completed':
        profile.status = Profile.ACTIVE
        
    elif request.POST.get('txn_type') == 'recurring_payment_profile_created':
        profile.status = Profile.PENDING

    profile.save()

    return HttpResponse()


class Billing(TemplateView):
    template_name = "payments/billing.html"

    def get_context_data(self, **kwargs):
        try:
            self.request.organization.payment
        except Profile.DoesNotExist:
            raise Http404
            
        context = {
            "strategies": Strategy.objects.all(),
            "organization": self.request.organization,
            "payment_form": PaymentForm()
        }
        context.update(kwargs)
        return context
        
    def post(self, *args, **kwargs):
        payment_form = PaymentForm(self.request.POST)
        if payment_form.is_valid():
            payment_strategy = Strategy.objects.get(
                name=payment_form.cleaned_data['plan']
            )
            payment = self.request.organization.payment
            
            paypal_data = dict(payment_form.cleaned_data, **{
                "CURRENCYCODE": "USD",
                "PROFILESTARTDATE": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S"),
                "DESC": "%s:%s" % (self.request.organization.name, payment_strategy.name),
                "BILLINGPERIOD": "Month",
                "BILLINGFREQUENCY": "1",
                "AMT": payment_strategy.price,
                "PAYERSTATUS": "verified",
            })
            paypal_data['FIRSTNAME'] = "%s : %s" % (
                self.request.organization.name,
                paypal_data['FIRSTNAME']
            )
            
            paypal = PayPal()

            try:
                paypal.ManageRecurringPaymentsProfileStatus(
                    PROFILEID=payment.paypal_id,
                    ACTION="Cancel"
                )
            except PayPalException as e:
                if e.message['L_ERRORCODE0'] not in ('11556', '11551'): 
                    raise e

            try:
                paypal_response = paypal.CreateRecurringPaymentsProfile(**paypal_data)
            except PayPalException as e:
                
                if e.message['L_ERRORCODE0'] == '10527':
                    payment_form._errors['ACCT'] = payment_form.error_class(
                        [e.message['L_LONGMESSAGE0']])
                
                return self.render_to_response(
                    self.get_context_data(
                        payment_form=payment_form,
                        payment_error=e.message['L_LONGMESSAGE0']
                    )
                )
                    
            valid_time = datetime.now() + relativedelta(months=+1, days=+1)

            old_strategy = payment.strategy
            
            payment.strategy = payment_strategy
            payment.valid_time = valid_time
            payment.paypal_id = paypal_response['PROFILEID']
            payment.status = Profile.PENDING
            
            admin_member = self.request.user.organization_member.get(
                organization=self.request.organization)
            
            payment.save(admin_memeber=admin_member)
            
            send_mail(
                'Qualitio Project, Payment profile updated for %s organization'
                % self.request.organization.name,
                render_to_string('payments/profile_update.mail',
                                 {"organization": self.request.organization,
                                  "old_strategy": old_strategy,
                                  "current_strategy": payment.strategy}),
                'Qualitio Notifications <notifications@qualitio.com>',
                self.request.organization.admins.values_list("email", flat=True))

            return redirect("/settings/billing/")

        return self.render_to_response(
            self.get_context_data(**{"payment_form": payment_form}))


class BillingCancel(RedirectView):
    url = "/settings/billing/"
    permanent = False
    
    def get(self, request, *args, **kwargs):
        payment = self.request.organization.payment
        
        admin_member = self.request.user.organization_member.get(
            organization=self.request.organization)

        payment.cancel(admin_memeber=admin_member)

        send_mail(
            'Qualitio Project, Payment profile cancled for %s organization'
            % self.request.organization.name,
            render_to_string('payments/profile_cancel.mail',
                             {"organization": self.request.organization}),
            'Qualitio Notifications <notifications@qualitio.com>',
            self.request.organization.admins.values_list("email", flat=True))

        
        return super(BillingCancel, self).get(request, *args, **kwargs)

qualitio/templates/payments/billing.html
{% extends "organizations/organization_settings.html" %}
{% load authorization %}

{% block settings-active-menu %}menu-item-billing{% endblock %}

{% block project_detail %}

<div class="billing">
  <h1>
    Billing <span>(Current account: {{ organization.payment.strategy }})</span>
    {% if organization.payment.strategy.price > 0 %}
    {% endif %}
  </h1>

  <table class="plans">
    <tr>
      <th>Plan</th>
      <th>Users</th>
      <th>Projects</th>
      <th>Price</th>
      <th>&nbsp;</th>
    </tr>

    {% for strategy in strategies %}
    <tr class="{% if organization.payment.strategy == strategy %}current{% endif %}{% if organization.payment.price > strategy.price %}disable{% endif %}">
      <td>{{ strategy.name }}</td>
      <td>
	{% if strategy.users == -1 %}
	Unlimited
	{% else %}
	Up to {{ strategy.users }}
	{% endif %}
	users
      </td>
      <td>Unlimited projects</td>
      <td>${{ strategy.price }}/month</td>
      <td>
	{% if strategy.price == 0 %}
	Free
	{% else %}
	{% if organization.payment.strategy == strategy %}
	
	{% if organization.payment.is_running %}
	<a href="#" name="{{ strategy.name }}" class="cancel-button">Cancel?</a>
	{% else %}
	Valid till: {{ organization.payment.valid_time }}
	{% endif %}
	
	{% else %}
	<a href="#" name="{{ strategy.name }}" class="buy-button">Buy</a>
	{% endif %}
	{% endif %}
      </td>
    </tr>
    {% endfor %}
  </table>

  <div class="payments_form action_form clearfix {% if request.method == "GET" %}hidden{% endif %}" >
    <form action="{% url organization_settings_billing %}" method="post" >
      {% csrf_token %}
      <div class="plan-information">
	Buy <span class="name"></span> plan?
      </div>
      {{ payment_error }}
      <div class="grid_8">
	<div class="address-details">
	  <h2>Address details</h2>
	  {{ payment_form.FIRSTNAME.label_tag }}
	  {{ payment_form.FIRSTNAME.errors.as_text }}
	  {{ payment_form.FIRSTNAME }}

	  {{ payment_form.LASTNAME.label_tag }}
	  {{ payment_form.LASTNAME.errors.as_text }}
	  {{ payment_form.LASTNAME }}

	  {{ payment_form.STREET.label_tag }}
	  {{ payment_form.STREET.errors.as_text }}
	  {{ payment_form.STREET }}

	  {{ payment_form.CITY.label_tag }}
	  {{ payment_form.CITY.errors.as_text }}
	  {{ payment_form.CITY }}

	  {{ payment_form.STATE.label_tag }}
	  {{ payment_form.STATE.errors.as_text }}
	  {{ payment_form.STATE }}

	  {{ payment_form.ZIP.label_tag }}
	  {{ payment_form.ZIP.errors.as_text }}
	  {{ payment_form.ZIP }}

	  {{ payment_form.COUNTRYCODE.label_tag }}
	  {{ payment_form.COUNTRYCODE.errors.as_text }}
	  {{ payment_form.COUNTRYCODE }}
	</div>

      </div>
      <div class="grid_8 clearfix">
	<div class="card-details">
	  <h2>Creditcard details</h2>
	  {{ payment_form.plan }}
	  {{ payment_form.CREDITCARDTYPE.label_tag }}
	  {{ payment_form.CREDITCARDTYPE.errors.as_text }}

	  {{ payment_form.CREDITCARDTYPE }}

	  {{ payment_form.ACCT.label_tag }}
	  {{ payment_form.ACCT.errors.as_text }}
	  {{ payment_form.ACCT }}

	  {{ payment_form.EXPDATE.label_tag }}
	  {{ payment_form.EXPDATE.errors.as_text }}
	  {{ payment_form.EXPDATE }}

	  {{ payment_form.CVV2.label_tag }}
	  {{ payment_form.CVV2.errors.as_text }}
	  {{ payment_form.CVV2 }}
	</div>
	<div class="footer clearfix">
	  <input class="button" type="submit" value="pay" />
	</div>
      </div>
    </form>
  </div>
  <div class="cancel_form action_form clearfix hidden" >
    <div class="plan-information">
      Really want to cancel <span class="name"></span> plan?
    </div>
    <a class="button no-button" href="#">No</a>
    <a class="button" href="{% url organization_settings_billing_cancel %}">Yes</a>
  </div>
</div>
<script>
    $(document).ready(function() {
	$('.buy-button').click( function() {
	    $("#id_plan").val($(this).attr("name"));
	    $(".plan-information .name").text($(this).attr("name"));
	    $(".cancel_form").hide();
	    $(".payments_form").show();
	    
	});
	$('.cancel-button').click(function() {
	    $(".plan-information .name").text($(this).attr("name"));
	    $(".payments_form").hide();
	    $(".cancel_form").show();
	});
	$('.no-button').click( function () {
	    $(".cancel_form").hide();
	});
    });
</script>

{% endblock %}